export { default as EditIcon } from './EditIcon'
export { default as CopyIcon } from './CopyIcon'
export { default as PlayIcon } from './PlayIcon'
export { default as VolumeIcon } from './VolumeIcon'
export { default as SettingIcon } from './SettingIcon'
export { default as PauseIcon } from './PauseIcon'
